[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise="0.6.1"
dotenv_codegen="0.15.0"
tokio = { version = "1.4.0", features = ["rt", "macros"] }